language: python
python:
  - "2.7"
  - "3"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - "pip install -qq pytest"
  - "pip install -qq pytest-cov"
  - "pip install -qq flake8"
  - "pip install coveralls --quiet"
  - "pip install ."

# command to run tests
script:
  - py.test -s --cov=py_linq --cov-report xml:/tmp/cov-py_linq.xml --junitxml=/tmp/py_linq.xml
  - flake8 --version
  - flake8 --ignore E501 py_linq tests

after_success:
  - coveralls
